BaytRSS/BaytRSS/Models/Career.cs
using BaytRSS.Helper;
using System;
using System.Collections.Generic;
using System.Xml;

namespace BaytRSS.Models
{
    public class Career
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public string Guid { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string Profile { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public DateTime PostedDate { get; set; }
        public string Division { get; set; }
        public static List<Career> RetrieveAllCareers(string baseAddress, string endPoint)
        {
            var payload = HttpClientHelper.HttpGet(baseAddress, endPoint);
            var careers = RetrieveItemsFromRss(payload);
            return careers;
        }
        private static List<Career> RetrieveItemsFromRss(string xml)
        {
            XmlDocument document = new XmlDocument();
            document.LoadXml(xml);
            var list = document.GetElementsByTagName("item");

            var careers = GetItems(list);
            return careers;
        }
        private static List<Career> GetItems(XmlNodeList node)
        {
            List<Career> careers = new List<Career>();
            foreach (XmlNode item in node)
            {
                Career career = new Career
                {
                    Id = System.Guid.NewGuid(),
                    Title = item?.SelectSingleNode("title")?.InnerText,
                    Link = item?.SelectSingleNode("link")?.InnerText,
                    Guid = item?.SelectSingleNode("guid")?.InnerText,
                    Description = item?.SelectSingleNode("description")?.InnerText,
                    Category = item?.SelectSingleNode("category")?.InnerText,
                    City = item?.SelectSingleNode("city")?.InnerText,
                    Profile = item?.SelectSingleNode("profile")?.InnerText,
                    Country = item?.SelectSingleNode("country")?.InnerText,
                    PostedDate = DateTime.Parse(item?.SelectSingleNode("posted_date")?.InnerText),
                    Division = item?.SelectSingleNode("division")?.InnerText
                };
                careers.Add(career);
            }

            return careers;
        }
    }
}

BaytRSS/BaytRSS/Controllers/CareersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BaytRSS.Helper;
using BaytRSS.Models;

namespace BaytRSS.Controllers
{
    public class CareersController : Controller
    {
        public static List<Career> careers;
        public CareersController()
        {
            if(careers == null)
                careers = Career.RetrieveAllCareers("https://www.rotanacareers.com/", "live-bookmarks/all-rss.xml");
        }
        // GET: Careers
        public ActionResult Index()
        {
            var sortedCareers = careers.OrderBy(car => car.Title);
            return View(sortedCareers);
        }

        public ActionResult CarrerById(string id)
        {
            var career = careers.FirstOrDefault(car => car.Id.ToString() == id);
            return View(career);
        }
    }
}

BaytRSS/BaytRSS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaytRSS.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BaytRSS/BaytRSS/Views/Careers/CarrerById.cshtml
@model BaytRSS.Models.Career
@{
    ViewBag.Title = "CareerById";
}

<h2>@Model.Title</h2>

<div>
    <h4>Career</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <div id="Title">
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
        </div>

        <dt>
            @Html.DisplayNameFor(model => model.Link)
        </dt>

        <div id="Link">
            <dd>
                @Html.DisplayFor(model => model.Link)
            </dd>
        </div>

        <dt>
            @Html.DisplayNameFor(model => model.Guid)
        </dt>

        <div id="Guid">
            <dd>
                @Html.DisplayFor(model => model.Guid)
            </dd>
        </div>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <div id="Description">
            <dd>
                @{
                    var dec = Model.Description;
                }
                @Html.Raw(dec)
            </dd>
        </div>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <div id="Category">
            <dd>
                @Html.DisplayFor(model => model.Category)
            </dd>
        </div>

        <dt>
            @Html.DisplayNameFor(model => model.Profile)
        </dt>

        <div id="Profile">
            <dd>
                @Html.DisplayFor(model => model.Profile)
            </dd>
        </div>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <div id="City">
            <dd>
                @Html.DisplayFor(model => model.City)
            </dd>
        </div>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <div id="Country">
            <dd>
                @Html.DisplayFor(model => model.Country)
            </dd>
        </div>

        <dt>
            @Html.DisplayNameFor(model => model.PostedDate)
        </dt>

        <div id="PostedDate">
            <dd>
                @Html.DisplayFor(model => model.PostedDate)
            </dd>
        </div>

        <dt>
            @Html.DisplayNameFor(model => model.Division)
        </dt>

        <div id="Division">
            <dd>
                @Html.DisplayFor(model => model.Division)
            </dd>
        </div>

    </dl>
</div>
<div id="GoogleMaps">
</div>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBSx_8D25Fc7YX9QofIsD9fStwgrF0-jL0&callback=initMap&libraries=places"></script>

<p>
    @Html.ActionLink("Back to List", "Index", "Careers", null, new { @class = "btn btn-primary" })
</p>

@Scripts.Render("~/Scripts/Maps")

BaytRSS/BaytRSS/Views/Careers/Index.cshtml
@model IEnumerable<BaytRSS.Models.Career>

@{
    ViewBag.Title = "Careers";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Profile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Division)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @{
                var title = item.Title;
            }
            @Html.ActionLink(title, "CarrerById", new { id = item.Id })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Profile)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Division)
        </td>
        <td>
            @Html.ActionLink("Details", "CarrerById", "Careers", new { id = item.Id }, new {@class = "btn btn-primary" })
        </td>
    </tr>
}

</table>

BaytRSS/BaytRSS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BaytRSS/BaytRSS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BaytRSS/BaytRSS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

BaytRSS/BaytRSS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Rotana Careers", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("All Careers", "Index", "Careers")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)
</body>
</html>